### PR TITLE
Add facades for PrimeReact's ToggleButton, Message, ProgressSpinner

### PR DESCRIPTION
**Pull request by rpiaggio**
Also very minor changes and our own facade for TooltipOptions.

### CODE REVIEW

**Comment by cquiroz** [comment]
Do you want to use prime's tooltips instead of floating ui?

**Comment by rpiaggio** [comment]
> Do you want to use prime's tooltips instead of floating ui?

I couldn't figure out how to (more or less easily) attach a floating ui tooltip to a prime component, since the facade seems to need a tag to attach to, not a component.

**Review by toddburnside — APPROVED** [review]
LGTM

**Comment by cquiroz** [comment]
> > Do you want to use prime's tooltips instead of floating ui?
> 
> 
> 
> I couldn't figure out how to (more or less easily) attach a floating ui tooltip to a prime component, since the facade seems to need a tag to attach to, not a component.

There is a syntax "withTooltip" you can use on components to add one

**Comment by rpiaggio** [comment]
> There is a syntax "withTooltip" you can use on components to add one

I'll give it a try, thank you.

**Comment by rpiaggio** [comment]
> There is a syntax "withTooltip" you can use on components to add one

It only seems to be available for `VdomTag`, forcing us to enclose all components in an extra tag. As discussed on Slack, maybe we should use Prime's mechanism for Prime components? I'll leave this in the facade for now, we can refactor later if we change our decision.

**Pull request merged**
