### PR TITLE
Move floatingui from Explore

### PR DESCRIPTION
**Pull request by toddburnside**

### CODE REVIEW

**Comment by armanbilge** [comment]
Before we merge this, can we add a test? I can push one up.

Because the facade is now living outside of explore its more vulnerable to accidental regressions.

**Comment by toddburnside** [comment]
> Before we merge this, can we add a test? I can push one up.
> 
> Because the facade is now living outside of explore its more vulnerable to accidental regressions.

Yes, that's a good idea.

**Comment by armanbilge** [comment]
Good thing I added a test, the sources were placed in the wrong directory 😛 

I didn't really know what I was doing, if there's a good way to make the test a little more interesting that could be good.

**Comment by toddburnside** [comment]
> the sources were placed in the wrong directory 😛

😬 I missed a directory layer. How embarrassing. 😝  Good catch.

**Comment by toddburnside** [comment]
> if there's a good way to make the test a little more interesting that could be good.

It's hard to make interesting tests for a lot of these facades. The only thing I can think of to make it "more interesting" is if we could simulate a mouse hover on the trigger. That causes additional DOM to appear.

**Comment by armanbilge** [comment]
Yup that's what I thought. But even though the generated HTML doesn't indicate there's a tooltip there, I'm confident-ish that the tooltip codepaths are getting invoked, which is really what we want.

**Pull request merged**
