### PR TITLE
Fix to chart race condition

### PR DESCRIPTION
**Pull request by rpiaggio**
Untested, that's why it's draft.

### CODE REVIEW

**Comment by toddburnside** [comment]
Unfortunately, this doesn't fix either the `StrictMode` or double click on target table issues. 😭

**Comment by rpiaggio** [comment]
> Unfortunately, this doesn't fix either the `StrictMode` or double click on target table issues. 😭

I had an error which I now fixed. I cannot reproduce the issue in explore thought to try it out. Can we test it?

**Review by toddburnside — APPROVED** [review]
This does seem to eliminate the remaining `TypeError: Cannot read properties of undefined (reading '0')` error message.

**Comment by rpiaggio** [comment]
> This does seem to eliminate the remaining `TypeError: Cannot read properties of undefined (reading '0')` error message.

Thank you very much for testing.

**Pull request merged**
